# Generated by Django 4.0.6 on 2022-08-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='is_staff',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
