# Generated by Django 4.0.6 on 2022-08-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_classes_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classes_taught',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.RemoveField(
            model_name='user',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
    ]
