# Generated by Django 4.0.6 on 2022-08-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('standard', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
