# Generated by Django 4.0.6 on 2022-08-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userregistermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classes_taught',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(default='null', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='standard',
            field=models.CharField(default='null', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stream',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
