# Generated by Django 4.0.6 on 2022-08-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='standard_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
